### ISSUE TITLE
Does Docker environment support Socket Programming assignment?

### ISSUE THREAD

**Issue by sumango3** [ANLAB-KAIST/KENSv3#129]
According to [Getting Started: Docker](https://github.com/ANLAB-KAIST/KENSv3/wiki/Getting-Started:-Docker), it only provides test-kens-*, which is TCP implementation related assignments.
Does it provide grading for Socket Programming assignment, which uses EchoAssignment.cpp and app/echo/echo?
Thank you in advance.

**Comment by Pusnow** [comment]
Yes, you can use Docker for the Socket Programming assignment.
