### ISSUE TITLE
Better to use explicit assertion macros

### ISSUE THREAD

**Issue by protos37** [ANLAB-KAIST/KENSv3#3]
It would be better to use explicit assertion macros, for example, using
```c++
EXPECT_EQ(ret, 0);
```
instead of
```c++
EXPECT_TRUE(ret == 0);
```
referencing google test [documentation](https://code.google.com/p/googletest/wiki/Primer).

I uploaded diff [here](https://gist.github.com/protos37/de7b61fe9495f804e3bb), please check and apply.

**Comment by leeopop** [comment]
내일 시험끝나는데 반영해놓을게요;

**Comment by leeopop** [comment]
finished
