### ISSUE TITLE
Cannot compile KENSv3 on Arch Linux

### ISSUE THREAD

**Issue by Narice** [ANLAB-KAIST/KENSv3#5]
Hello,
Today I tried installing KENSv3 on Arch Linux and found out that it might be impossible due to the already constructed object solution file:
```
/usr/bin/ld: ../../solution/E_TCPSolution_linux_amd64.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIC
```
OS: Arch Linux x86_64
Kernel: Linux 5.3.1-arch1-1-ARCH

**Comment by Pusnow** [comment]
We've not support recent version of gcc yet.

Try [KENSv3-Docker](https://github.com/ANLAB-KAIST/KENSv3-Docker), if you are familiar with docker .

**Comment by Narice** [comment]
Thank you for your very quick response!
I will check the docker version of KENS

**Comment by Pusnow** [comment]
Now, KENSv3 supports GCC from 5 to 9.
I've also confirmed it works well with archlinux (gcc 9.1.0).

Try it, and let me know, if there is any problem.

**Comment by Narice** [comment]
It works great now
I'm really impressed by your work, dedication, and responsiveness
Thank you!
